/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testdb;

import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author elmnshawy
 */
public class Rform extends javax.swing.JFrame {

    static Connection con;
    DefaultTableModel dtm;

    ArrayList<Integer> cbdepartmentindex = new ArrayList<>();
    ArrayList<Integer> studentindex = new ArrayList<>();

    public Rform() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        dtm = new DefaultTableModel();
        dtm.addColumn("Name");
        dtm.addColumn("ID");
        dtm.addColumn("Gender");
        dtm.addColumn("Depatrment");
        fillcombobox();
        fillTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TF_id = new javax.swing.JTextField();
        TF_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RbtMale = new javax.swing.JRadioButton();
        RbtFemale = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        CBdepatrment = new javax.swing.JComboBox<>();
        bt_Add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbshow = new javax.swing.JTable();
        bt_update1 = new javax.swing.JButton();
        bt_delete1 = new javax.swing.JButton();
        bt_clear2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(125, 125, 125));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Name");

        TF_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_idActionPerformed(evt);
            }
        });

        TF_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_nameActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student ID");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Gendr");

        Group1.add(RbtMale);
        RbtMale.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RbtMale.setSelected(true);
        RbtMale.setText("Male");

        Group1.add(RbtFemale);
        RbtFemale.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RbtFemale.setText("Female");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Department");

        CBdepatrment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBdepatrmentActionPerformed(evt);
            }
        });

        bt_Add.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        bt_Add.setText("Add");
        bt_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AddActionPerformed(evt);
            }
        });

        Tbshow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Gender", "Department"
            }
        ));
        Tbshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbshowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbshow);

        bt_update1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        bt_update1.setText("update");
        bt_update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_update1ActionPerformed(evt);
            }
        });

        bt_delete1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        bt_delete1.setText("delete");
        bt_delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_delete1ActionPerformed(evt);
            }
        });

        bt_clear2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        bt_clear2.setText("clear");
        bt_clear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clear2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_name, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RbtMale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(RbtFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TF_id)
                            .addComponent(CBdepatrment, 0, 289, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_clear2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(bt_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_delete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_update1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addGap(35, 35, 35)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RbtMale)
                    .addComponent(RbtFemale))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CBdepatrment)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_clear2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_update1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_idActionPerformed

    private void TF_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_nameActionPerformed

    private void CBdepatrmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBdepatrmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBdepatrmentActionPerformed

    private void bt_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AddActionPerformed
        // TODO add your handling code here:

        if (!TF_name.getText().isEmpty() && !TF_id.getText().isEmpty()) {

            try {
                String name = TF_name.getText();
                int id = Integer.parseInt(TF_id.getText());

                String gender;

                if (RbtMale.isSelected()) {
                    gender = RbtMale.getText().toString();
                } else {
                    gender = RbtFemale.getText().toString();
                }

                String department = CBdepatrment.getSelectedItem().toString();

                PreparedStatement stm = con.prepareStatement("insert into students (student_name , student_id , student_gender, student_department) \n"
                        + "values( ? , ? , ? , ? )");

                stm.setString(1, name);
                stm.setInt(2, id);
                stm.setString(3, gender);
                stm.setInt(4, cbdepartmentindex.get(CBdepatrment.getSelectedIndex()));

                stm.executeUpdate();
                JOptionPane.showMessageDialog(this, "added sucssufly");
                dtm.addRow(new Object[]{name, id, gender, department});
                Tbshow.setModel(dtm);

            } catch (SQLException ex) {
                Logger.getLogger(Rform.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_bt_AddActionPerformed

    private void TbshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbshowMouseClicked
        // TODO add your handling code here:

        TF_name.setText(Tbshow.getValueAt(Tbshow.getSelectedRow(), 0).toString());
        TF_id.setText(Tbshow.getValueAt(Tbshow.getSelectedRow(), 1).toString());
        CBdepatrment.setSelectedItem(Tbshow.getValueAt(Tbshow.getSelectedRow(), 3));

        if (Tbshow.getValueAt(Tbshow.getSelectedRow(), 2) != null) {

            if (Tbshow.getValueAt(Tbshow.getSelectedRow(), 2).toString().equalsIgnoreCase("male")) {
                RbtMale.setSelected(true);
            } else {
                RbtFemale.setSelected(true);
            }
        }

    }//GEN-LAST:event_TbshowMouseClicked

    private void bt_update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_update1ActionPerformed
        // TODO add your handling code here:

        if (!TF_name.getText().isEmpty() && !TF_id.getText().isEmpty()) {

            try {
                String name = TF_name.getText();
                int id = Integer.parseInt(TF_id.getText());

                String gender;

                if (RbtMale.isSelected()) {
                    gender = RbtMale.getText().toString();
                } else {
                    gender = RbtFemale.getText().toString();
                }

                String department = CBdepatrment.getSelectedItem().toString();

                PreparedStatement stm = con.prepareStatement("update  students set student_name =? , student_gender =? , student_department=? where student_id =? ");

                stm.setString(1, name);
                //stm.setInt(2,id );
                stm.setString(2, gender);
                stm.setInt(3, cbdepartmentindex.get(CBdepatrment.getSelectedIndex()));
                stm.setInt(4, studentindex.get(Tbshow.getSelectedRow()));
                stm.executeUpdate();
                JOptionPane.showMessageDialog(this, "added sucssufly");
                dtm.addRow(new Object[]{name, id, gender, department});
                // Tbshow.setModel(dtm);
                fillTable();
            } catch (SQLException ex) {
                Logger.getLogger(Rform.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_bt_update1ActionPerformed

    private void bt_delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_delete1ActionPerformed
        try {
            // TODO add your handling code here:
            PreparedStatement stm = con.prepareStatement("delete from students where student_id =?");
            stm.setInt(1, studentindex.get(Tbshow.getSelectedRow()));
            stm.executeUpdate();
            JOptionPane.showMessageDialog(this, "deleted sucssufly");
            fillTable();

        } catch (SQLException ex) {
            Logger.getLogger(Rform.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_bt_delete1ActionPerformed

    private void bt_clear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clear2ActionPerformed
        // TODO add your handling code here:
        TF_id.setText("");
        TF_name.setText("");
        CBdepatrment.setSelectedItem("IT");
        RbtMale.setSelected(true);
    }//GEN-LAST:event_bt_clear2ActionPerformed

    private void fillcombobox() {
        try {
            PreparedStatement stm = con.prepareStatement("select depart_name , depart_id from departments ");
            ResultSet rs = stm.executeQuery();

            while (rs.next()) {

                CBdepatrment.addItem(rs.getString(1));
                cbdepartmentindex.add(rs.getInt(2));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Rform.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void fillTable() {

        dtm.setRowCount(0);
        try {
            PreparedStatement stm = con.prepareStatement("select student_name , student_id , student_gender , depart_name from students , departments where students.student_department = departments.depart_id ");
            ResultSet rs = stm.executeQuery();

            while (rs.next()) {

                dtm.addRow(new Object[]{rs.getString(1), rs.getInt(2), rs.getString(3), rs.getString(4)});
                studentindex.add(rs.getInt(2));

            }
            Tbshow.setModel(dtm);

        } catch (SQLException ex) {
            Logger.getLogger(Rform.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localHost:3306/test1", "root", "Mkh@3032024M");

        } catch (ClassNotFoundException ex) {
            // Logger.getLogger(ConnectionDBtest.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        } catch (SQLException ex) {
            //Logger.getLogger(ConnectionDBtest.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Rform().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Rform.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBdepatrment;
    private javax.swing.ButtonGroup Group1;
    private javax.swing.JRadioButton RbtFemale;
    private javax.swing.JRadioButton RbtMale;
    private javax.swing.JTextField TF_id;
    private javax.swing.JTextField TF_name;
    private javax.swing.JTable Tbshow;
    private javax.swing.JButton bt_Add;
    private javax.swing.JButton bt_clear2;
    private javax.swing.JButton bt_delete1;
    private javax.swing.JButton bt_update1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
